### ISSUE TITLE
Dependencies: Compatible SQLAlchemy

### ISSUE THREAD

**Issue by anhdangqb** [Galileo-Galilei/kedro-mlflow-tutorial#13]
When running this `pip install -e src/.`
The install stuck at looking for compatible SQLAlchemy

**Comment by Galileo-Galilei** [comment]
Hi @anhdangqb, sorry for that. I had pinned a very old mlflow version because the package had a couple of bugs back when I wrote the tutorial, but they were fixed in the most recent versions. You can either use `mlflow==1.26.1` in your requirements or pull the last version of main and it should be all right. 

Notice that the tutorial still use ``kedro==0.16.6``, but I plan to release 0.17.x and 0.18.x versions in the coming weeks, as required by #9. I've already started that in #12.
