### ISSUE TITLE
run_id in MLflow tag is a timestamp and not an ID

### ISSUE THREAD

**Issue by Chouffe** [Galileo-Galilei/kedro-mlflow-tutorial#5]
After following the tutorial and inspecting the results via the MLflow UI, the `run_id` set as a tag is a timestamp and not an id.
I am wondering what is wrong here.

![image](https://user-images.githubusercontent.com/2046602/132677447-5708cb68-c63a-487b-a59d-864c23cea35e.png)

**Comment by Galileo-Galilei** [comment]
Hi, 

it may sounds confusing but all the tags set in mlflow come from [``Kedro Journal``](https://kedro.readthedocs.io/en/0.16.5/08_logging/02_journal.html#context-journal-record). This is an object of the ``kedro==0.16.x`` versions which tracks some metadata about your run (including the parameters passed to CLI), and the internal Kedro's (not mlflow) ``run_id`` which is just a timestamp. This timestamp is useful in case you use Kedro's native versioning abilities for datasets. 

You should really not care too much about it for two reasons: 
- it is not very informative: you already know the start date of your mlflow run
- it is deprecated in ``kedro==0.17.x``  and will be removed in ``kedro==0.18.x``. 
I plan to update the example to use a more recent version of kedro (I initially used kedro 0.16.x because when I created this repo 0.17.x was in early stage and have some really annoying bugs, but kedro 0.17.4 seems stable.
